_target_: src.policy.onestage.OneStagePolicy
state_user_latent_dim:
state_item_latent_dim:
state_transformer_enc_dim:
state_transformer_n_head:
state_transformer_d_forward:
state_transformer_n_layer:
state_dropout_rate:

model_path:
loss:
l2_coef:
device:
