# @package _global_

base_dir: /Users/alexander.kazakov/Documents/rl_in_recsys
user_meta_file: ${base_dir}/dataset/user_features_Pure_fillna.csv
item_meta_file: ${base_dir}/dataset/video_features_basic_Pure_fillna.csv
train_file: ${base_dir}/dataset/log_session_4_08_to_5_08_Pure.csv

# output_path: output/Kuairand_Pure/
# log_name: user_KRMBUserResponse_lr0.0001_reg0_nlayer2

