# AGENT_CLASS='DDPG'
# GAMMA=0.9
# REWARD_FUNC='get_immediate_reward'
# N_ITER=20000
# START_STEP=100
# INITEP=0.01
# ELBOW=0.1
# EXPLORE_RATE=1.0
# BS=128

_target_: src.agent.ddpg.DDPG
config:
  gamma: 0.9
  reward: src.reward.get_immediate_reward
  n_iter: 20000
  # train_every_n_step: int
  start_policy_train_at_step: 100
  # initial_epsilon: float
  # final_epsilon: float
  elbow_epsilon: 0.1
  explore_rate: 1.0
  # do_explore_in_train: bool
  # check_episode: bool
  # save_path: str
  # actor_lr: float
  # actor_decay: float
  batch_size: int
  critic_lr:
  critic_decay: 
  target_mitigate_coef: 